name: 'Prerender website'
description:
  'Converts/pre-renders single page application (SPA) into static html files'
author: 'Anton Stoychev'
inputs:
  website_root:
    required: true
    description:
      'Directory where your /index.html is and where you will get the
      pre-rendered output'
  max_concurrent_pages:
    description: 'Maximum number of parallel page rendering'
    default: '3'
  meta_prerender_only:
    description:
      'Resulting *.html files have only the <head>...</head> changed. Set this
      to "1" to enable.'
  selector_to_wait_for:
    description:
      'When provided the html will be captured only after the provided DOM
      element selector exists.'
  blocked_partial_urls:
    description:
      'Multi-line input. Each line is treated as partial of a URL which you want
      to block when pre-rendering'
  canonical_base_url:
    description:
      'Enables sitemap generation and uses the provided url instead of original
      base'
runs:
  using: 'node16'
  main: 'dist/prerender-github-action/index.js'
branding:
  icon: 'layout'
  color: 'green'
